#pragma once


#define MAX_CREATURES 20
#define MAX_ENTITIES 30

#define SCREEN_WIDTH 1000
#define SCREEN_HEIGHT 760
#define LIMIT_FPS 60

#define CHUNK_UNITS 32
#define CHUNK_HEIGHT CHUNK_UNITS*50
#define CHUNK_SIZE CHUNK_UNITS*CHUNK_UNITS
#define PLAYER_START (CHUNK_UNITS/2)*50

#define GRID_UNITS 30